### PR TITLE
feat: Adding at_getting_started very simple examples in Dart

### PR DESCRIPTION
**Pull request by cconstab**
very simple atKey and notification examples as simple starting point

**- What I did**
Added simple (but powerful) examples to get people started with dart
**- How I did it**
Migrate code from my personal repo and added basic ReadMe and asciinema examples
**- How to verify it**
ran and recorded the results in the Readme
**- Description for the changelog**
Added pre starting examples using Dart and atKeys/Notifications.

### CODE REVIEW

**Comment by murali-shris** [comment]
Reviewed. looks good to me

**Comment by cconstab** [comment]
> Reviewed. looks good to me

I resync with trunk so is fine to approve/merge TY

**Comment by cconstab** [comment]
> Reviewed. looks good to me

Could you approve for me?

**Review by gkc — APPROVED** [review]
LGTM

**Pull request merged**
